### PR TITLE
Convert cggnn/graphs and workflow configure to use config files

### LINKED ISSUE #272: Abstract out graph deep learning functionality to an external plugin system
This would be implemented as follows
1. The `cggnn` submodule would be renamed to `graphs` to reflect the change in its responsibilities and disambiguate from the `cg-gnn` model. (This would also future-proof against a potential expansion to creating tissue/region graphs in addition to cell graphs that I think we'd want to do, but that's far outside the scope of this issue.)
2. This repository, SPT, would reduce graph functionality in the `graphs` submodule to the following:
   * **Output graphs**: Given a configuration with controlled fields like `graph_specs.yml` (i.e., an API call), output a data artifact with consistent structure to file that contains cell graphs constructed by SPT.
   * **Upload transformations**: Upload consistent output (presumed to be transformed versions of the output graphs, e.g., by a deep learning model), which includes importance scores per histological structure, to the database.
   * Other functions that can utilize the consistent input and output to do simple stuff with, like graph plotting.
3. Graph deep learning functionality would be abstracted and moved to an external plugin system.
   * Each plugin would have
      * A filled-out but study-agnostic version of `graph_specs.yml`, so it can be applied to any study uploaded by SPT.
      * A Docker container that would set up their environment to run their model, run their model on the data artifact, and output results in the format that SPT expects so they can be uploaded to SPT (importance scores to start with, but potentially more stuff like model checkpoints later down the line).
   * These Docker containers would be derived from a template GitHub repo that will be created to close this issue.
4. SPT `workflow` would be modified to get pinned versions of each plugin's Docker container to run the deep learning workflow(s).
   * (A later update will add functionality to `db` that triggers deep learning runs on upload of new studies in a similar fashion.)

Addition of new graph deep learning plugins to SPT would be done in three steps:
1. **Exploratory stage**: a user would evaluate if their deep learning model is good or not by manually using the output and upload functions described in the prior section and examining their results locally or in an SPT instance after upload.
2. **Proposal stage**: If a user determines that their graph model is a good candidate for inclusion into SPT as a default graph deep learning plugin that should be run on every new study imported into SPT, they would containerize their model according to the Docker template defined for the external plugin system, upload it to a GitHub repo or equivalent, and open an issue or pull request for SPT to include their plugin.
3. **Inclusion stage**: The SPT maintainers would quality check the proposed plugin and, if found to be worth including, upload the container to the SPT Docker page and modify SPT code to pull down and use that Docker image by default in SPT.

Implementation plan.
1. (Optional, but complementary.) Implement #271. Since we're abstracting out GNNs, this would allow us to reduce the number of dependencies that need to be installed to run SPT.
   * We could even go further and remove the pytorch dependency and just output graphs as numpy arrays since any graph deep learning would just be done in a separate Docker image.
2. #275
3. #277
4. #278, which closes #247 in part.
5. [Create the Docker plugin template repo and pattern and conform the `cg-gnn` model to it.](https://github.com/nadeemlab/spt-plugin/issues/2) This would also exemplify the pattern of proposal and inclusion into SPT.
   * Once this step is complete and tested, this issue would be closed.
6. Other features facilitated by this refactor:
   a. Apply the new plugin process to close #268
   b. This should give us a better idea of how to close the rest of #247 and if we want to reorganize workflow into the plugin system as well
   c. Add triggers to `db` to run the default GNN plugins on each new study when they're uploaded, if [spt-plugin#2](https://github.com/nadeemlab/spt-plugin/issues/2) is implemented in a compatible way

This functionality would be implemented in lieu of #269 and #270.

### PR DESCRIPTION
**Pull request by CarlinLiao**
This closes #272 and #278 by
* Renaming the `cggnn` submodule to `graphs`
* Converting most `graphs` functionality to control by config file and not CLI args
* Converting `workflow configure` to be controlled by config file and not CLI args

#276 and [spt-plugin#3](https://github.com/nadeemlab/spt-plugin/pull/3) are necessary prerequisites for this PR as #276 is still dependent on an older version of spt-cg-gnn Docker image that will need to be updated once spt-plugin#3 is accepted. Until those are merged and that Docker image updated, this will remain an untested draft PR.

### CODE REVIEW

**Comment by CarlinLiao** [comment]
This was also accidentally merged by me at the same time as #276, but this wasn't a PR that was ready to merge. I think what happened is that I pressed the wrong button in the VS Code version control UI (but I didn't think that it was possible to merge pull requests in VS Code). Checking resolution methods...

**Comment by CarlinLiao** [comment]
I suspect but can't confirm what happened was that
1. my local SPT repo was sitting in the issue272 branch
2. I used the VS Code UI to switch to main branch and sync for new incoming commits and upload outgoing commits, but the switch only switched my branch reference and not repo state,
3. so all the commits from issue272 got uploaded to main as if rebasing.

Consequently, there's no single merge commit to undo, all of the commits from issue275 and issue272 are in main as if I commit them to the main branch directly as I was working on them. Conveniently, however, the branches happened to be worked on serially over the last few weeks so it should be easy to split: every commit [after this one](https://github.com/nadeemlab/SPT/commit/04e2feffb4bbf315b83843b9f489bca9c61bb182) is from issue275 until [this one](https://github.com/nadeemlab/SPT/commit/98bec1757ca9fccd1ad26d1018b71f9033fae576), after which it's commits for issue272.

**Comment by jimmymathews** [comment]
Yes, that it what I was going to recommend (not sure about whether `--hard` is necessary though).
I believe the issue branches can be worked on normally after this. I'll give it try.

**Comment by jimmymathews** [comment]
It looks OK to me.

**Comment by CarlinLiao** [comment]
Thank you for fixing my mistake, it looks good on my end as well. I don't see a method to re-open these pull requests, though I may not have the necessary permissions for that.

**Comment by jimmymathews** [comment]
Hm well the branches are still there (e.g. `issue272`) so I think you can just make a new PR.

**Pull request merged**
