### PR TITLE
Add cg-gnn graph generation and plotting

### PR DESCRIPTION
**Pull request by CarlinLiao**
Pursuant to #239. Editing the implementation to support parallelization with Nextflow will come in the next PR.

All tests pass, with the exception of some apiserver and db module tests. I'm opening this PR anyway since I made no changes to any code that runs there, and I suspect that has to do more with [this issue I'm having with my environment](https://github.com/nadeemlab/SPT/issues/243#issuecomment-1804405286) rather than the code in this PR.

### CODE REVIEW

**Comment by CarlinLiao** [comment]
Converting to draft due to issues observing when testing after a fresh `make clean-docker-images`, specifically `make unit-test-cggnn`. These don't appear to be due to the changes introduced by this PR, but rather an issue arising from the reorganization effort for studies into their own separate databases, similar to #243.

```
┃ explore ┈┈┈11-09 20:54:56 [  INFO   ] db.feature_matrix_extractor: Retrieving stratification from database.
11-09 20:54:56 [  ERROR  ] db.database_connection:68: Failed to connect to database: spt-db-testing-only, default_study_lookup
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/spatialprofilingtoolbox/cggnn/scripts/explore_classes.py", line 55, in <module>
    strata = extractor.extract_cohorts(study=args.study)['strata']
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/spatialprofilingtoolbox/db/feature_matrix_extractor.py", line 253, in extract_cohorts
    return self._extract_cohorts(study)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/spatialprofilingtoolbox/db/feature_matrix_extractor.py", line 256, in _extract_cohorts
    stratification = self._retrieve_derivative_stratification_from_database()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/spatialprofilingtoolbox/db/feature_matrix_extractor.py", line 267, in _retrieve_derivative_stratification_from_database
    puller.pull(measured_only=True)
  File "/usr/local/lib/python3.11/dist-packages/spatialprofilingtoolbox/db/stratification_puller.py", line 35, in pull
    self.stratification = self._retrieve_stratification(measured_only=measured_only)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/spatialprofilingtoolbox/db/stratification_puller.py", line 42, in _retrieve_stratification
    study_names = retrieve_study_names(self.database_config_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/spatialprofilingtoolbox/db/database_connection.py", line 163, in retrieve_study_names
    with DBCursor(database_config_file=database_config_file) as cursor:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/spatialprofilingtoolbox/db/database_connection.py", line 113, in __init__
    super().__init__(**kwargs)
  File "/usr/local/lib/python3.11/dist-packages/spatialprofilingtoolbox/db/database_connection.py", line 69, in __init__
    raise exception
  File "/usr/local/lib/python3.11/dist-packages/spatialprofilingtoolbox/db/database_connection.py", line 65, in __init__
    super().__init__(self.make_connection(credentials))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/spatialprofilingtoolbox/db/database_connection.py", line 88, in make_connection
    return connect(
           ^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "spt-db-testing-only" (192.168.128.2), port 5432 failed: FATAL:  database "default_study_lookup" does not exist
```

**Comment by jimmymathews** [comment]
`make unit-test-cggnn` all pass for me, including `test_explore`. The error seems to indicate outdated db image. `make force-rebuild-data-loaded-images`?

**Comment by CarlinLiao** [comment]
I don't know if both these steps were necessary to fix it but getting the new commits to main and then rebuilding the data loaded images worked to fix the unit test cggnn errors.

However, module-test-ondemand is still failing because its environments can't initialize. For some reason, when setting up apiserver's Docker runs cggnn's init file, which causes an error because torch isn't installed.

```
Container readiness checking timed out after 120 seconds
Printing docker compose logs in case of error:
spt-ondemand-testing  | Traceback (most recent call last):
spt-ondemand-testing  |   File "/usr/local/bin/spt", line 8, in <module>
spt-ondemand-testing  |     sys.exit(main_program())
spt-ondemand-testing  |              ^^^^^^^^^^^^^^
spt-ondemand-testing  |   File "/usr/local/lib/python3.11/site-packages/spatialprofilingtoolbox/entry_point/cli.py", line 78, in main_program
spt-ondemand-testing  |     submodules_with_commands = [
spt-ondemand-testing  |                                ^
spt-ondemand-testing  |   File "/usr/local/lib/python3.11/site-packages/spatialprofilingtoolbox/entry_point/cli.py", line 79, in <listcomp>
spt-ondemand-testing  |     name for name in submodule_names if len(get_commands(name)) > 0
spt-ondemand-testing  |                                             ^^^^^^^^^^^^^^^^^^
spt-ondemand-testing  |   File "/usr/local/lib/python3.11/site-packages/spatialprofilingtoolbox/entry_point/cli.py", line 18, in get_commands
spt-ondemand-testing  |     _files = files(f'spatialprofilingtoolbox.{submodule_name}')
spt-ondemand-testing  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spt-ondemand-testing  |   File "/usr/local/lib/python3.11/importlib/resources/_common.py", line 22, in files
spt-ondemand-testing  |     return from_package(get_package(package))
spt-ondemand-testing  |                         ^^^^^^^^^^^^^^^^^^^^
spt-ondemand-testing  |   File "/usr/local/lib/python3.11/importlib/resources/_common.py", line 53, in get_package
spt-ondemand-testing  |     resolved = resolve(package)
spt-ondemand-testing  |                ^^^^^^^^^^^^^^^^
spt-ondemand-testing  |   File "/usr/local/lib/python3.11/importlib/resources/_common.py", line 44, in resolve
spt-ondemand-testing  |     return cand if isinstance(cand, types.ModuleType) else importlib.import_module(cand)
spt-ondemand-testing  |                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spt-ondemand-testing  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
spt-ondemand-testing  |     return _bootstrap._gcd_import(name[level:], package, level)
spt-ondemand-testing  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spt-ondemand-testing  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
spt-ondemand-testing  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
spt-ondemand-testing  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
spt-ondemand-testing  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
spt-ondemand-testing  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
spt-ondemand-testing  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
spt-ondemand-testing  |   File "/usr/local/lib/python3.11/site-packages/spatialprofilingtoolbox/cggnn/__init__.py", line 4, in <module>
spt-ondemand-testing  |     from spatialprofilingtoolbox.cggnn.dataset import (
spt-ondemand-testing  |   File "/usr/local/lib/python3.11/site-packages/spatialprofilingtoolbox/cggnn/dataset.py", line 5, in <module>
spt-ondemand-testing  |     from torch.utils.data import ConcatDataset, DataLoader, SubsetRandomSampler
spt-ondemand-testing  | ModuleNotFoundError: No module named 'torch'
```

The stuff in init isn't necessarily crucial and can be removed, but I think they make the code cleaner. Maybe we can edit ondemand to not use the CLI or the CLI to no run the init of every module?

**Comment by jimmymathews** [comment]
The CLI probes the each submodule to get the script (command) names without these having to be hard-coded and duplicated. At some point I tried to remove all unnecessary third-party imports from these inits, for this reason.
In general I don't think the convenience of `from toplevelpackage import symbol` is worth it. Compared with the benefit of making imports more transparent, by causing fewer hidden imports as a result. (Like `import spatialprofilingtoolbox.cggnn`, which one might use to ascertain the interface of the module independently from its implementation. Hidden `import torch`.)

**Comment by jimmymathews** [comment]
I think this mechanic of python's import system for subpackages is well-adapted to a division between interface and implementation. Interface in __init__ for all to peruse, implementation in real submodules.

**Comment by CarlinLiao** [comment]
All tests now pass.

**Comment by jimmymathews** [comment]
Testing in progress, likely merge soon.

**Pull request merged**
