### PR TITLE
Containerize test running and reduce development environment requirements

### PR DESCRIPTION
**Pull request by jimmymathews**
This PR addresses #88 .

## Acceptance

- `make test` runs on your development machine without a hitch!

### CODE REVIEW

**Comment by jimmymathews** [comment]
On re-running this myself, I have encountered a few hitches.

- Make sure a local Postgres isn't running before starting, usually using one of:
```sh
sudo systemctl stop postgresql
pg_ctl stop -D $data_directory # where data_directory is gotten using psql:  "show data_directory;"
```
- Run `make docker-compositions-rm` liberally after run failures. Eventually we will need a better "cleanup on error" pattern.

**Comment by jimmymathews** [comment]
There is also a missing dependency declaration in the Makefile: the module Docker images should be built before any test target. This went unnoticed before because the docker daemon happily provided previous images when requested.

I'm fixing this, and hopefully also getting rid of the need to deal with the presence of a local Postgres service completely. Docker compose should be able to spin up containers in their own network not interfering with the host.

**Comment by jimmymathews** [comment]
I hit a bit of a snag: It seems that actual Docker Engine is not available for Mac at all. All the basic docker commands are provided by Docker Desktop instead, but networking capability via Docker Desktop is limited.
Specifically, the "user-defined bridge" network mode seems to be available only on Linux.

**Comment by CarlinLiao** [comment]
Fair enough. I think we should just say we're not supporting MacOS. In virtually all realistic use cases it'll probably be running on a Linux server.

**Comment by jimmymathews** [comment]
I think I have overcome this particular issue... they may have implemented this already, despite come comments I read that seemed supported by remarks in the docker documentation. Initially I was unable to reach a container at its default hostname, but this was my own error.

**Comment by jimmymathews** [comment]
Ok, I have deprecated all the stuff related to managing a local postgres service.
The docker compositions are now forced to live in their own isolated network created at test time.
I am getting all build steps OK and all tests passing on Mac laptop. Whether or not postgres is running.

The integration test (proximity metrics) is pretty long-running, in the future we might want to modify it to do less work. Could be done by truncating the number of features it assesses, for example. I think it is doing a few thousand phenotype pairs.

I have also added short messages regarding the setup/teardown of testing environments, so that the terminal doesn't look like it is hanging during those 5 seconds or so.

**Comment by jimmymathews** [comment]
The recent commits should reduce the runtime of the long-running computation test by about 50%.

**Comment by CarlinLiao** [comment]
With the new changes, all tests pass except this one.

```
Testing temp ...Expecting value: line 1 column 1 (char 0)
1,5d0
< {
<     "specimen measurement study names": [
<         "Test project - Melanoma intralesional IL2 (Hollmann lab) - measurement"
<     ]
< }
API query for measurement study names failed.
Printing docker compose logs in case of error:
spt-apiserver-testing  | INFO:     Started server process [1]
spt-apiserver-testing  | INFO:     Waiting for application startup.
spt-apiserver-testing  | INFO:     Application startup complete.
spt-apiserver-testing  | INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
spt-apiserver-testing  | INFO:     172.18.0.5:39376 - "GET /specimen-measurement-study-names HTTP/1.1" 200 OK
spt-apiserver-testing  | INFO:     172.18.0.5:39378 - "GET /specimen-measurement-study-names HTTP/1.1" 200 OK
spt-countsserver-testing  | 10-23 22:19:32 [  DEBUG  ] spt countsserver start:22: Searching for source data in: /countsserver/source_data/
spt-countsserver-testing  | 10-23 22:19:33 [  INFO   ] spt countsserver start: countsserver is ready to accept connections.
spt-db-testing            | 
spt-db-testing            | PostgreSQL Database directory appears to contain a database; Skipping initialization
spt-db-testing            | 
spt-db-testing            | 2022-10-23 22:19:32.900 UTC [1] LOG:  starting PostgreSQL 14.5 (Debian 14.5-2.pgdg110+2) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
spt-db-testing            | 2022-10-23 22:19:32.900 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
spt-db-testing            | 2022-10-23 22:19:32.903 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
spt-db-testing            | 2022-10-23 22:19:32.907 UTC [27] LOG:  database system was interrupted; last known up at 2022-10-23 22:17:38 UTC
spt-db-testing            | 2022-10-23 22:19:34.314 UTC [27] LOG:  database system was not properly shut down; automatic recovery in progress
spt-db-testing            | 2022-10-23 22:19:34.316 UTC [27] LOG:  redo starts at 0/1813F38
spt-db-testing            | 2022-10-23 22:19:34.319 UTC [27] LOG:  redo done at 0/192CF78 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
spt-db-testing            | 2022-10-23 22:19:34.335 UTC [1] LOG:  database system is ready to accept connections

NETWORK ID     NAME                                   DRIVER    SCOPE
297d209a625f   apiserver_default                      bridge    local
6093a5391160   apiserver_isolated_temporary_test      bridge    local
590df880e50e   bridge                                 bridge    local
93782ddbb68b   countsserver_default                   bridge    local
fe28f040fd25   countsserver_isolated_temporary_test   bridge    local
4d1a701ff3b7   db_default                             bridge    local
0235d6b55adf   db_isolated_temporary_test             bridge    local
d96b81f9a610   host                                   host      local
e1ed26bb469a   none                                   null      local
b07d096cb2b3   workflow_isolated_temporary_test       bridge    local

CONTAINER ID   IMAGE                        COMMAND                  CREATED         STATUS                            PORTS                    NAMES
8602404b8721   nadeemlab/spt-countsserver   "spt countsserver st…"   4 seconds ago   Up 3 seconds (health: starting)   0.0.0.0:8016->8016/tcp   spt-countsserver-testing
22af8dacd6dd   nadeemlab/spt-db-preloaded   "docker-entrypoint.s…"   4 seconds ago   Up 3 seconds (health: starting)   0.0.0.0:5432->5432/tcp   spt-db-testing
bfc5c645d001   nadeemlab/spt-apiserver      "uvicorn app.main:ap…"   4 seconds ago   Up 3 seconds (health: starting)   0.0.0.0:8080->8080/tcp   spt-apiserver-testing
................................................................ Failed.        (1s)
```

**Review by CarlinLiao — APPROVED** [review]
After a couple of git cleans, all tests pass. Approved.

**Pull request merged**
